#!/usr/bin/env bash
#Run Nginx as Nginx
#sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
#sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
#sudo -u nginx service nginx restart
pkill apache2
chown nginx /etc/nginx/nginx.conf
chmod u+r /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
